### ISSUE TITLE
Build command should work regardless of the app key

### ISSUE THREAD

**Issue by vkaelin** [adonisjs/assembler#7] opened 2020-05-02 20:51 UTC
## Package version
^2.0.3

## Node.js and npm version
14.1.0
6.14.4

## Sample Code (to reproduce the issue)
Run the commande `node ace build` without an **APP_KEY** in your `.env` file give you this error:

``
✖  fatal     ✖  fatal     Exception: E_MISSING_ENV_KEY: Make sure to define environment variable APP_KEY
    at Env.getOrFail (/home/valentin/www/website/server/node_modules/@adonisjs/env/build/src/Env.js:200:19)
    at Object.<anonymous> (/home/valentin/www/website/server/config/app.ts:29:35)
    at Module._compile (internal/modules/cjs/loader.js:1176:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1196:10)
    at Module.load (internal/modules/cjs/loader.js:1040:32)
    at Function.Module._load (internal/modules/cjs/loader.js:929:14)
    at Module.require (internal/modules/cjs/loader.js:1080:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at /home/valentin/www/website/server/node_modules/require-all/index.js:56:46
    at Array.forEach (<anonymous>)
``

**Comment by thetutlage** [comment] 2020-05-03 04:47
I tried reproducing the issue and it works fine for me without the `.env` file. Here's a repo for same https://github.com/thetutlage/assembler-issue-7

- Just clone it, there will be no `.env` and hence no `APP_KEY`
- Run `node ace build`, and it works as expected.

Can you help me reproduce the issue with the repo I created?

**Comment by vkaelin** [comment] 2020-05-03 12:32
Ok I have found the issue but I still don't know why it happens.
Here are the steps to reproduce:

Create a Model in your application
Create a Command and inside the ``handle`` method try to create a new instance of the Model.

The error message will appear.

Example:
**Models/Champion.ts:**
```
import { DateTime } from 'luxon'
import { BaseModel, column } from '@ioc:Adonis/Lucid/Orm'

export default class Champion extends BaseModel {
  @column({ isPrimary: true })
  public id: number

  @column.dateTime({ autoCreate: true })
  public createdAt: DateTime

  @column.dateTime({ autoCreate: true, autoUpdate: true })
  public updatedAt: DateTime
}
```

**commands/Test.ts:**
```
import { flags } from '@adonisjs/ace'
import { BaseCommand } from '@adonisjs/ace'
import Champion from 'App/Models/Champion'

export default class Test extends BaseCommand {
  public static commandName = 'import:champions'
  public static description = 'Import CSV File containing champions list'

  @flags.string({ description: 'Path of the CSV file to import' })
  public path: string

  public static settings = {
    loadApp: true,
  }

  public async handle () {
    this.logger.info('Hello world!')

    await Champion.create({})
  }
}
```

**Comment by thetutlage** [comment] 2020-05-03 15:05
Yup, that's the issue. You have to little careful with commands, since AdonisJS has to load them to generate the `commands manifest` file. So all imports has to be inside the `handle` method.

The following code should work.

```ts
import { flags } from '@adonisjs/ace'
import { BaseCommand } from '@adonisjs/ace'

export default class Test extends BaseCommand {
  public static commandName = 'import:champions'
  public static description = 'Import CSV File containing champions list'

  @flags.string({ description: 'Path of the CSV file to import' })
  public path: string

  public static settings = {
    loadApp: true,
  }

  public async handle () {
    const Champion = (await import('App/Models/Champion')).default
    this.logger.info('Hello world!')
    await Champion.create({})
  }
}
```

I can get into the detailing of why the import has to be inside the `handle` method and what are the alternatives, if we decide to remove this limitations. So lemme know, if you are curious to know the internals

**Comment by vkaelin** [comment] 2020-05-03 17:02
Thanks I don't have any error anymore!

Does this kind of import have a special name ? I'm not really used to this syntax and it would be useful for me to do some research about it.

**Comment by thetutlage** [comment] 2020-05-03 18:49
These are dynamic imports and part of the ESM spec. Will close the issue now

**Closed by thetutlage** 2020-05-03 18:49 UTC
Labels: question
